### ISSUE TITLE
Problem building executable

### ISSUE THREAD

**Issue by rsignell-usgs** [metocean/docker-roms-public#1]
I followed the `Readme.md` instructions, successfully ran the upwelling test, and accessed the output netcdf files on my host machine.  Hurrah!

I then tried creating an `include` directory on my host machine, copied the `upwelling.h` file in there did:
```
export myapp=UPWELLING

docker-compose run build
```
but got back
```
Starting dockerromspublic_build_volumes_1
ERROR: Cannot start service build: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"cd\\\": executable file not found in $PATH\"\n"
```

**Comment by rsoutelino** [comment]
@rsignell-usgs fixed by https://github.com/metocean/docker-roms-public/commit/151127c51ea171a8e90283be2bd76fb883d3143e

I forgot to declare the ENV var in the Dockerfile. I've rebuilt the docker and it works here now. Could you sync this repo, re-pull the docker image, and try again? Let me know if there are still issues. 

Note that I found an option in `docker-compose run` that eliminates the need to create an env var with your app name, which is quite handy.  So the run command changed: https://github.com/metocean/docker-roms-public/commit/151127c51ea171a8e90283be2bd76fb883d3143e#diff-04c6e90faac2675aa89e2176d2eec7d8R41
